/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiBlogRouteImport } from './routes/api/blog'
import { Route as Api1a23RouteImport } from './routes/api/1a23'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogRoute = ApiBlogRouteImport.update({
  id: '/api/blog',
  path: '/api/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const Api1a23Route = Api1a23RouteImport.update({
  id: '/api/1a23',
  path: '/api/1a23',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/1a23': typeof Api1a23Route
  '/api/blog': typeof ApiBlogRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/1a23': typeof Api1a23Route
  '/api/blog': typeof ApiBlogRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/1a23': typeof Api1a23Route
  '/api/blog': typeof ApiBlogRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/1a23' | '/api/blog'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/1a23' | '/api/blog'
  id: '__root__' | '/' | '/api/1a23' | '/api/blog'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Api1a23Route: typeof Api1a23Route
  ApiBlogRoute: typeof ApiBlogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog': {
      id: '/api/blog'
      path: '/api/blog'
      fullPath: '/api/blog'
      preLoaderRoute: typeof ApiBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/1a23': {
      id: '/api/1a23'
      path: '/api/1a23'
      fullPath: '/api/1a23'
      preLoaderRoute: typeof Api1a23RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Api1a23Route: Api1a23Route,
  ApiBlogRoute: ApiBlogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
